### ISSUE TITLE
How to get rid of "Choose your search engine" window

### ISSUE THREAD

**Issue by mburghol** [grafana/grafana-kiosk#137]
Every time I start the browser under Windows 11 with the following command 
grafana-kiosk.windows.amd64.exe -URL ‘myurl’ -login-method apikey -apikey mykey
`
since the last update of chrome I can do this promptly
![Screenshot 2024-07-29 172521](https://github.com/user-attachments/assets/8a403c41-f596-4f3a-92f6-04353b243d8f)

If I click on ‘set as default’ - the window will appear again next time.
I may be overlooking a parameter - would be nice if someone could help me

**Comment by mburghol** [comment]
Hello Brian,

[this ](https://stackoverflow.com/questions/78798750/how-to-get-rid-of-choose-your-search-engine-dialog-in-chrome-v-127-on-selenium) should be the flag...

I have no idea about go - but I somehow managed to execute the build file and tried it out.

I have added
`		chromedp.flag(“disable-search-engine-choice-screen”, true),
`
in _utils.go_ - at first glance this seems to be the solution

**Comment by S-Fitzy-Picnic** [comment]
is there a way to have the Kiosk pass browser execution arguments through to the browser? it looks like there is an argument that should disable this flag, but it would also be handy if we can trigger other browser arguments through the kiosk.

This would be handy for a number of reasons, but also for future cases like this so that we can immediately implement browser specific fixes while waiting for an update/fix for the Kiosk.

**Comment by ctih** [comment]
When will a new release be released? 😊

**Comment by S-Fitzy-Picnic** [comment]
> When will a new release be released? 😊

looks like the update is pending an approval
> https://github.com/grafana/grafana-kiosk/pull/138

**Comment by Moritz-M** [comment]
Any updates? The pull request is now already one month old
